//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    /// <summary>
    /// Контекст базы данных для Kamenetskiy_payment.
    /// Подключается через строку "Kamenetskiy_paymentEntities" из App.config.
    /// </summary>
    public partial class Kamenetskiy_paymentEntities : DbContext
    {
        /// <summary>
        /// Конструктор, инициализирующий подключение по имени строки в App.config.
        /// </summary>
        public Kamenetskiy_paymentEntities()
            : base("name=Kamenetskiy_paymentEntities")
        {
        }

        /// <summary>
        /// Метод, вызываемый при построении модели EF.
        /// </summary>
        /// <param name="modelBuilder">Построитель модели.</param>
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // Не использовать Code First — схема определяется существующей базой данных
            throw new UnintentionalCodeFirstException();
        }

        /// <summary>
        /// Таблицы базы данных
        /// </summary>
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Users> Users { get; set; }

        /// <summary>
        /// Единый экземпляр контекста (Singleton)
        /// </summary>
        private static Kamenetskiy_paymentEntities context;

        /// <summary>
        /// Возвращает единый экземпляр контекста базы данных
        /// </summary>
        public static Kamenetskiy_paymentEntities GetContext()
        {
            if (context == null)
                context = new Kamenetskiy_paymentEntities();
            return context;
        }
    }
}
